### ISSUE TITLE
Auto replace partial fix

### ISSUE THREAD

**Issue by Bigboibigdum** [VJ-HLR-Developers/Half-Life-Resurgence#94]
Last I checked, resurgence npcs dont work with scripted sequences and other campaign stuff yet. But if my knowledge of goldsrc carries over to source I think I know how you could fix some of it.

In goldsrc, scripted sequences look for an npc with a specific name set by the mapper. So if the npc models have all the animations from the original models used for scripted sequences, (or just completely use the original models,) would it be possible to have the replaced npc's name carry over to the new npc? This would probably fix stuff like retinal scanners.

(But I'm more used to goldsrc mapping so sorry if this whole thing doesnt apply to source)

**Comment by Cpt-Hazama** [comment]
We already do what you suggest, however because the original entity gets removed this messes with the map. I should also mention that its just straight up impossible for us to make HLR work 100% in the campaign because we are missing A LOT of essentials from the source code in lua. So sadly, such a thing can't and won't be fixed 😔

**Comment by Bigboibigdum** [comment]
Actually uh yeah dont know much about github so maybe shouln't be saying this on a closed issue???????????
but...
Did the mappers for hl1 and hl2 name every npc or just ones that needed names? If it's the second, maybe there could be an option to check if an npc has a name and if it does, it doesn't get replaced?

**Comment by DrVrej** [comment]
Unfortunately it is a mix, sometimes a pointless NPC is named and sometimes an essential NPC isn't named
